import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  subsets: ["arabic", "latin"], // Arabic + English
  weight: ["400", "500", "700"], // choose the weights you need
  variable: "--font-cairo", // make it a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairo.variable}  font-sans`}>
        <div className="lg:max-w-[1140px] mx-auto bg-[#191919]">{children}</div>
      </body>
    </html>
  );
}
